### PR TITLE
Fix/deployment optimiation

### LINKED ISSUE #18: Lambda fails to deploy due to size
Our fat jar became too fat after adding Tesseract:

```shell
OpinionsStack: deploying...
[0%] start: Publishing b1428aad666c85067babbce12e9982014f7aec59f1fb586e537476d527766047:current
[100%] success: Published b1428aad666c85067babbce12e9982014f7aec59f1fb586e537476d527766047:current
OpinionsStack: creating CloudFormation changeset...
 0/6 | 4:05:40 AM | UPDATE_IN_PROGRESS   | AWS::CDK::Metadata          | CDKMetadata 
 0/6 | 4:05:40 AM | UPDATE_IN_PROGRESS   | AWS::Lambda::Function       | opinions-webhook (opinionswebhook0ED7E5E6) 
 1/6 | 4:05:41 AM | UPDATE_COMPLETE      | AWS::CDK::Metadata          | CDKMetadata 
 2/6 | 4:05:42 AM | UPDATE_FAILED        | AWS::Lambda::Function       | opinions-webhook (opinionswebhook0ED7E5E6) Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: d4a0431b-16d9-4d51-9ce7-8b7841d3518d)
        new Function (/home/madhead/Projects/opinions-bot/.cdk/node_modules/@aws-cdk/aws-lambda/lib/function.ts:460:35)
        \_ new OpinionsStack (/home/madhead/Projects/opinions-bot/.cdk/lib/opinions-stack.ts:28:33)
        \_ Object.<anonymous> (/home/madhead/Projects/opinions-bot/.cdk/bin/cdk.ts:15:1)
        \_ Module._compile (internal/modules/cjs/loader.js:1256:30)
        \_ Module.m._compile (/home/madhead/Projects/opinions-bot/.cdk/node_modules/ts-node/src/index.ts:837:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
        \_ Object.require.extensions.<computed> [as .ts] (/home/madhead/Projects/opinions-bot/.cdk/node_modules/ts-node/src/index.ts:840:12)
        \_ Module.load (internal/modules/cjs/loader.js:1105:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:967:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
        \_ main (/home/madhead/Projects/opinions-bot/.cdk/node_modules/ts-node/src/bin.ts:226:14)
        \_ Object.<anonymous> (/home/madhead/Projects/opinions-bot/.cdk/node_modules/ts-node/src/bin.ts:485:3)
        \_ Module._compile (internal/modules/cjs/loader.js:1256:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
        \_ Module.load (internal/modules/cjs/loader.js:1105:32)
        \_ Function.Module._load (internal/modules/cjs/loader.js:967:14)
        \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
        \_ /usr/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
 2/6 | 4:05:43 AM | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack  | OpinionsStack The following resource(s) failed to update: [opinionswebhook0ED7E5E6]. 
 2/6 | 4:06:12 AM | UPDATE_IN_PROGRESS   | AWS::CDK::Metadata          | CDKMetadata 
 3/6 | 4:06:12 AM | UPDATE_COMPLETE      | AWS::Lambda::Function       | opinions-webhook (opinionswebhook0ED7E5E6) 

 ❌  OpinionsStack failed: Error: The stack named OpinionsStack is in a failed state: UPDATE_ROLLBACK_COMPLETE
    at /home/madhead/Projects/opinions-bot/.cdk/node_modules/aws-cdk/lib/api/util/cloudformation.ts:165:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at waitFor (/home/madhead/Projects/opinions-bot/.cdk/node_modules/aws-cdk/lib/api/util/cloudformation.ts:76:20)
    at Object.deployStack (/home/madhead/Projects/opinions-bot/.cdk/node_modules/aws-cdk/lib/api/deploy-stack.ts:167:7)
    at CdkToolkit.deploy (/home/madhead/Projects/opinions-bot/.cdk/node_modules/aws-cdk/lib/cdk-toolkit.ts:152:24)
    at main (/home/madhead/Projects/opinions-bot/.cdk/node_modules/aws-cdk/bin/cdk.ts:229:16)
    at initCommandLine (/home/madhead/Projects/opinions-bot/.cdk/node_modules/aws-cdk/bin/cdk.ts:172:9)
**************************************************
*** Newer version of CDK is available [1.60.0] ***
*** Upgrade recommended                        ***
**************************************************
The stack named OpinionsStack is in a failed state: UPDATE_ROLLBACK_COMPLETE
```

### PR DESCRIPTION
**Pull request by sleshJdev**
Should fix #18 issue

I filter out unused dependencies using classifiers. I tried to play around gradle-javacpp plugin but seems it doesn't work with kotlin gradle dsl, no idea why. I raised an [issue](https://github.com/bytedeco/gradle-javacpp/issues/2) 

Current build size 47M:
```
$ du -sh build/libs/opinions-bot-all.jar 
47M     build/libs/opinions-bot-all.jar
```

### CODE REVIEW

**Comment by madhead** [comment]
How does this magic work?

**Comment by sleshJdev** [comment]
> How does this magic work?

Actually it's not the magic. I use classifier which is especially the current evn's arch and OS to specify precisely what native library I need. I had to manually declare transitive dependencies thought,. for each you provide two dependency deflation one for wrapper (java interface) and one for native library

**Comment by sleshJdev** [comment]
@madhead thanks for a hint about `gradlePluginPortal()` it helped a lot. I reworked PR using `gradle-javacpp-platform` plugin. Now it looks more concise

**Comment by sleshJdev** [comment]
I added lambda layer where to I extracted tess data. Now bundle has size ~36MB. I think it's fine now. I also had to increase ram to 1024 MB because it didn't process images in a reasonable time(I couldn't get any response, no error were found in logs). @madhead what your opinion?

**Comment by madhead** [comment]
Thank you!

**Comment by madhead** [comment]
@sleshJdev, I think you should make a PR to `.cdk` directory of this repo to benefit from the layers :)

**Comment by sleshJdev** [comment]
> @sleshJdev, I think you should make a PR to `.cdk` directory of this repo to benefit from the layers and tune RAM :)

Sorry? It's already done. What did you mean?

**Comment by madhead** [comment]
No, it's not done yet. Make a PR?

**Pull request merged**
