### PR TITLE
"rssparser" module

### PR DESCRIPTION
**Pull request by sleshJdev**
Mistakenly, I have not committed "rssparser" module. This PR fixes that.

### CODE REVIEW

**Comment by madhead** [comment]
Why do you parse XML manually, and not via KtRssParser or so?

**Comment by sleshJdev** [comment]
> Why do you parse XML manually, and not via KtRssParser or so?

It doesn't support this type of feed, unfortunatelly

**Comment by madhead** [comment]
What feed are we talking about?

**Comment by sleshJdev** [comment]
> What feed are we talking about?

These two:
1. http://insidejava.libsyn.com/rss - inside java podcast
2. https://inside.java/feed.xml - inside java news

**Comment by sleshJdev** [comment]
hi @madhead 

What do you think?

**Comment by madhead** [comment]
@sleshJdev, sorry for the delay.

[Here](https://github.com/JavaBy/opinions-bot/blob/dec894cdb02720948ee9b428cd1797fc44d0cd93/inside-java-podcast-poster/src/main/kotlin/by/jprof/telegram/opinions/insidejava/Handler.kt#L50) I parsed Inside Java podcast RSS with KtRssReader library and it worked well. What's the problem to use it? It should work.

**Comment by sleshJdev** [comment]
> @sleshJdev, sorry for the delay.
> 
> [Here](https://github.com/JavaBy/opinions-bot/blob/dec894cdb02720948ee9b428cd1797fc44d0cd93/inside-java-podcast-poster/src/main/kotlin/by/jprof/telegram/opinions/insidejava/Handler.kt#L50) I parsed Inside Java podcast RSS with KtRssReader library and it worked well. What's the problem to use it? It should work.

Yeah, it works fine for podscast rss, now try to parse https://inside.java/feed.xml(inside java news): I added inside java news crawler but KtRssReader wasn't able to handle its format I had to add new library for that, that is the reasoning...

**Comment by madhead** [comment]
Probably there is another library supporting both Atom and RSS: https://github.com/rometools/rome.

Can we use a library?

**Comment by madhead** [comment]
I'll be moving this to JavaBy/jprof_by_bot as this is not only opinions bot anymore and besides that I want more modular structure in the project.

One day I'll reimplement this news pipeline there or feel free to do that yourself.

**Pull request closed without merging**
