### PR TITLE
Just for fun

### PR DESCRIPTION
**Pull request by isadounikau**

### CODE REVIEW

**Comment by madhead** [comment]
@isadounikau, I'm afraid this PR collides with the other, more feature-rich: https://github.com/JavaBy/opinions-bot/pull/9, so I'll probably reject it due to conflicts when that one is accepted :(

Thank you for the contribution anyway!

**Comment by isadounikau** [comment]
Sure, just try to flow Kotlin code styles, not Java ;)

**Comment by sleshJdev** [comment]
> Sure, just try to follow Kotlin code styles, not Java ;)

A few questions:
1. Is there any accepted kotlin code guideline or you use own?
2. Do you really think your version of code formatting looks better?

**Comment by madhead** [comment]
1. At least there is one on the Kotlin site: https://kotlinlang.org/docs/reference/coding-conventions.html. Android developers also use Google's guide: https://developer.android.com/kotlin/style-guide.

**Pull request closed without merging**
